name: ShellCheck

on:
  push:
  workflow_dispatch:

permissions: read-all

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master